<a href="https://colab.research.google.com/github/Schiavi13/analisis-impacto-covid19-en-inversion-ecoeficiencia-empresarial-2019-2023/blob/luis_001/src/merge_datasets_ambiental_general_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Unificación de datasets ambiental y general del año 2021

In [ ]:
# importar librerias
import pandas as pd
print("Carga de librerías exitosa")

Carga de librerías exitosa

In [ ]:
# Carga datasets ambiental y general
df_ambiental_2021 = pd.read_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/ambiental/2021_eas_ambiental.csv")
df_ambiental_2021.head()

,id_empresa,periodo,id_sector,sector_desc,gastos_totales,gasto_gestion_amb,contrata_personal_amb,realiza_inv_red_emision_aire,realiza_inv_ahorro_agua,realiza_inv_inst_med_agua,...,realiza_otras_inv_amb,realiza_gasto_red_emision_aire,realiza_gasto_ahorro_agua,realiza_gasto_inst_med_agua,realiza_gasto_disp_desechos,realiza_gasto_protec_suelo,realiza_gasto_evita_ruido_vibra,realiza_gasto_terceros_amb,realiza_gasto_energia_limp,realiza_otros_gastos_amb
0,10001,2021,I1,alojamiento,"1.682.975,00","0,00",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,10002,2021,I1,alojamiento,"1.710.641,00","0,00",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,10003,2021,I1,alojamiento,"6.854.236,00","0,00",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,10004,2021,I1,alojamiento,"6.000.326,00","0,00",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,10005,2021,I2,expendio de alimentos,"22.229.918,00","171.785,00",1,0,0,0,...,0,0,1,0,1,0,0,1,0,0

In [ ]:
df_general_2021 = pd.read_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/general/2021_eas_general.csv")
df_general_2021.head()

,id_empresa,anio_inicio,periodo,id_sector_general,total_ingresos,personal_remunerado,gasto_remuneracion_personal,gasto_personal_total,personal_mujeres,personal_hombres,personal_ocupado,imp_ind_com,imp_otros,gasto_servicios_publicos,gasto_energia_electrica,gasto_gas_natural
0,10001,1992,2021,I1,2777410,25,632893,632893,14,11,25,29535,5717,126832,73346,86686
1,10002,1994,2021,I1,2563253,15,370129,370129,16,0,16,42943,398369,120294,230549,40434
2,10003,2016,2021,I1,7517713,47,1433906,1478298,30,44,74,90691,36867,161682,830041,129562
3,10004,2017,2021,I1,8334016,76,1324830,1324830,33,43,76,58338,34267,198765,223978,0
4,10005,1957,2021,I2,22229918,44,2329352,2641280,63,106,169,67097,375721,296660,957094,80015

Se unifican los datasets mediante un inner join con el id de la empresa

In [ ]:
# Merge de los dos datasets por campo id_empresa
df_servicios_unificado_2021 = pd.merge(df_ambiental_2021, df_general_2021, on="id_empresa", how="inner")
df_servicios_unificado_2021.head()

,id_empresa,periodo_x,id_sector,sector_desc,gastos_totales,gasto_gestion_amb,contrata_personal_amb,realiza_inv_red_emision_aire,realiza_inv_ahorro_agua,realiza_inv_inst_med_agua,...,gasto_remuneracion_personal,gasto_personal_total,personal_mujeres,personal_hombres,personal_ocupado,imp_ind_com,imp_otros,gasto_servicios_publicos,gasto_energia_electrica,gasto_gas_natural
0,10001,2021,I1,alojamiento,"1.682.975,00","0,00",0,0,0,0,...,632893,632893,14,11,25,29535,5717,126832,73346,86686
1,10002,2021,I1,alojamiento,"1.710.641,00","0,00",0,0,0,0,...,370129,370129,16,0,16,42943,398369,120294,230549,40434
2,10003,2021,I1,alojamiento,"6.854.236,00","0,00",0,0,0,0,...,1433906,1478298,30,44,74,90691,36867,161682,830041,129562
3,10004,2021,I1,alojamiento,"6.000.326,00","0,00",0,0,0,0,...,1324830,1324830,33,43,76,58338,34267,198765,223978,0
4,10005,2021,I2,expendio de alimentos,"22.229.918,00","171.785,00",1,0,0,0,...,2329352,2641280,63,106,169,67097,375721,296660,957094,80015

In [ ]:
# inspecciona el dataframe unificado
df_servicios_unificado_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6066 entries, 0 to 6065
Data columns (total 39 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id_empresa                       6066 non-null   int64
 1   periodo_x                        6066 non-null   int64
 2   id_sector                        6066 non-null   object
 3   sector_desc                      6066 non-null   object
 4   gastos_totales                   6066 non-null   object
 5   gasto_gestion_amb                6066 non-null   object
 6   contrata_personal_amb            6066 non-null   int64
 7   realiza_inv_red_emision_aire     6066 non-null   int64
 8   realiza_inv_ahorro_agua          6066 non-null   int64
 9   realiza_inv_inst_med_agua        6066 non-null   int64
 10  realiza_inv_disp_desechos        6066 non-null   int64
 11  realiza_inv_protec_suelo         6066 non-null   int64
 12  realiza_inv_evita_ruido_vibra    6066 non-null   int64
 13  realiza_inv_energia_limp         6066 non-null   int64
 14  realiza_otras_inv_amb            6066 non-null   int64
 15  realiza_gasto_red_emision_aire   6066 non-null   int64
 16  realiza_gasto_ahorro_agua        6066 non-null   int64
 17  realiza_gasto_inst_med_agua      6066 non-null   int64
 18  realiza_gasto_disp_desechos      6066 non-null   int64
 19  realiza_gasto_protec_suelo       6066 non-null   int64
 20  realiza_gasto_evita_ruido_vibra  6066 non-null   int64
 21  realiza_gasto_terceros_amb       6066 non-null   int64
 22  realiza_gasto_energia_limp       6066 non-null   int64
 23  realiza_otros_gastos_amb         6066 non-null   int64
 24  anio_inicio                      6066 non-null   int64
 25  periodo_y                        6066 non-null   int64
 26  id_sector_general                6066 non-null   object
 27  total_ingresos                   6066 non-null   object
 28  personal_remunerado              6066 non-null   int64
 29  gasto_remuneracion_personal      6066 non-null   int64
 30  gasto_personal_total             6066 non-null   int64
 31  personal_mujeres                 6066 non-null   int64
 32  personal_hombres                 6066 non-null   int64
 33  personal_ocupado                 6066 non-null   int64
 34  imp_ind_com                      6066 non-null   object
 35  imp_otros                        6066 non-null   object
 36  gasto_servicios_publicos         6066 non-null   int64
 37  gasto_energia_electrica          6066 non-null   object
 38  gasto_gas_natural                6066 non-null   int64
dtypes: int64(30), object(9)
memory usage: 1.8+ MB

Existen columnas con el mismo nombre en ambos datasets, por lo tanto pandas les modifica el nombre, a continuación se deja una sola con el nombre original.

In [ ]:
# Elimina columna periodo repetida
df_servicios_unificado_2021.drop(columns=["periodo_y"], inplace=True)
df_servicios_unificado_2021.rename(columns={"periodo_x":"periodo"}, inplace=True)
print(df_servicios_unificado_2021.columns)

Index(['id_empresa', 'periodo', 'id_sector', 'sector_desc', 'gastos_totales',
       'gasto_gestion_amb', 'contrata_personal_amb',
       'realiza_inv_red_emision_aire', 'realiza_inv_ahorro_agua',
       'realiza_inv_inst_med_agua', 'realiza_inv_disp_desechos',
       'realiza_inv_protec_suelo', 'realiza_inv_evita_ruido_vibra',
       'realiza_inv_energia_limp', 'realiza_otras_inv_amb',
       'realiza_gasto_red_emision_aire', 'realiza_gasto_ahorro_agua',
       'realiza_gasto_inst_med_agua', 'realiza_gasto_disp_desechos',
       'realiza_gasto_protec_suelo', 'realiza_gasto_evita_ruido_vibra',
       'realiza_gasto_terceros_amb', 'realiza_gasto_energia_limp',
       'realiza_otros_gastos_amb', 'anio_inicio', 'id_sector_general',
       'total_ingresos', 'personal_remunerado', 'gasto_remuneracion_personal',
       'gasto_personal_total', 'personal_mujeres', 'personal_hombres',
       'personal_ocupado', 'imp_ind_com', 'imp_otros',
       'gasto_servicios_publicos', 'gasto_energia_electrica',
       'gasto_gas_natural'],
      dtype='object')

## Verificación de consistencia de id_empresa e id_sector
Se comparan los id_sector e id_sector_general, y si son inconsistentes se busca la razón para realizar ajustes o eliminar registros.

In [ ]:
# Extrae id_sector diferentes
condicion_diferente_Sector = df_servicios_unificado_2021['id_sector'] != df_servicios_unificado_2021['id_sector_general']
df_servicios_unificado_2021.loc[condicion_diferente_Sector,
                                ['id_empresa',
                                 'id_sector',
                                 'total_ingresos',
                                 'id_sector_general']]

      id_empresa id_sector total_ingresos id_sector_general
22         10030        LN        2638582               LN1
113        10146        LN       79592726               LN1
120        10156        LN       52674938               LN1
129        10169         S       80601613                J1
139        10183         S       10727402                J1
...          ...       ...            ...               ...
5870       19122        LN        4772892               LN1
5874       19126        LN        6601220               LN1
6042       15375        LN        4096636               LN1
6054       15389        LN       28026875               LN1
6058       15393         S       76959664                J1

[368 rows x 4 columns]

Se evidencia que el sector "LN1" en id_sector_general tiene un número extra, se puede ajustar a "LN" para que coincida sin modificar los datos. Por otro lado, existen id_sector que no tienen relación, se aislan y se eliminan del análisis estos registros.

In [ ]:
# Corrige id_sector_general LN1 a LN
df_servicios_unificado_2021['id_sector_general'] = df_servicios_unificado_2021['id_sector_general'].mask(df_servicios_unificado_2021['id_sector_general']=='LN1', 'LN')
condicion_diferente_Sector = df_servicios_unificado_2021['id_sector'] != df_servicios_unificado_2021['id_sector_general']
df_servicios_unificado_2021.loc[condicion_diferente_Sector,
                                ['id_empresa',
                                 'id_sector',
                                 'total_ingresos',
                                 'id_sector_general']]

      id_empresa id_sector total_ingresos id_sector_general
129        10169         S       80601613                J1
139        10183         S       10727402                J1
532        10562         S       52698982                J1
793        10892         S        5289630                J1
808        10910         S        1685470                J1
1049       11231         S        6794007                J1
1062       11246         S        4771505                J1
1066       11250         S        1657633                J1
1196       11415         S      304819150                J1
1198       11417         S      304819150                J1
1203       11422         S        1997446                J1
1206       11425         S        3689895                J1
1209       11427         S        1345084                J1
1212       11430         S      118579231                J1
1366       11628         S       10981324                J1
1386       11656         S        2363843                J1
1552       11892         S       63459581                J1
2030       12629         S        1223467                J1
2035       12637         S        2905411                J1
2238       12929         S        6794480                J1
2248       12950         S         395075                J1
2350       13106         S        4124216                J1
2351       13108         S        2569578                J1
2410       17661         S       77340146                J1
2698       18623         S        2102626                J1
2699       19418         S        9894951                J1
2765       19451         S      304819150                J1
2780       18680         S        4517749                J1
2933       18845         S        3665868                J1
3044       19477         S        1578322                J1
3096       19860         S       22723260                J1
3099       19545         S       50608618                J1
3120       19882         S        1255628                J1
3296       20351         S        8699528                J1
4330       14078         S        4120034                J1
4331       14079         S       12046967                J1
4613       17819         S       27321860                J1
4649       18381         S       28125136                J1
6058       15393         S       76959664                J1

Las actividades de exhibición de películas cinematográficas y videos, con el id de sector J1, están codificadas como "Otros servicios",s e realiza el ajuste

In [ ]:
df_servicios_unificado_2021['id_sector'] = df_servicios_unificado_2021['id_sector'].mask((df_servicios_unificado_2021['id_sector']=='S') & (df_servicios_unificado_2021['id_sector_general']=='J1'), 'J1')
condicion_diferente_sector = df_servicios_unificado_2021['id_sector'] != df_servicios_unificado_2021['id_sector_general']
df_servicios_unificado_2021.loc[condicion_diferente_sector,
                                ['id_empresa',
                                 'id_sector',
                                 'total_ingresos',
                                 'id_sector_general']]

Empty DataFrame
Columns: [id_empresa, id_sector, total_ingresos, id_sector_general]
Index: []

## Exporta datos
Exporta el dataframe unificado a la carpeta de datasets unificados

In [ ]:
# Exporta el dataframe como csv
df_servicios_unificado_2021.to_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/unificados/2021_eas_unificado.csv", index=False)