<a href="https://colab.research.google.com/github/Schiavi13/analisis-impacto-covid19-en-inversion-ecoeficiencia-empresarial-2019-2023/blob/luis_001/src/merge_datasets_ambiental_general_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Unificación de datasets ambiental y general del año 2023

In [ ]:
# importar librerias
import pandas as pd
print("Carga de librerías exitosa")

Carga de librerías exitosa

In [ ]:
# Carga datasets ambiental y general
df_ambiental_2023 = pd.read_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/ambiental/2023_eas_ambiental.csv")
df_ambiental_2023.head()

,id_empresa,periodo,id_sector,sector_desc,gastos_totales,gasto_gestion_amb,contrata_personal_amb,realiza_inv_red_emision_aire,realiza_inv_ahorro_agua,realiza_inv_inst_med_agua,...,realiza_otras_inv_amb,realiza_gasto_red_emision_aire,realiza_gasto_ahorro_agua,realiza_gasto_inst_med_agua,realiza_gasto_disp_desechos,realiza_gasto_protec_suelo,realiza_gasto_evita_ruido_vibra,realiza_gasto_terceros_amb,realiza_gasto_energia_limp,realiza_otros_gastos_amb
0,10429,2023,H1,auxiliares del transporte,141276673,331267,1,1,1,0,...,1,1,1,0,1,0,1,1,0,1
1,10213,2023,H1,auxiliares del transporte,141276673,331267,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
2,13851,2023,H1,auxiliares del transporte,141276673,331267,1,0,0,0,...,1,1,0,0,0,0,1,0,0,0
3,10439,2023,H1,auxiliares del transporte,34597790,180809,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
4,13853,2023,H1,auxiliares del transporte,34597790,180809,0,0,0,0,...,0,1,0,0,1,1,1,1,0,0

In [ ]:
df_general_2023 = pd.read_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/general/2023_eas_general.csv")
df_general_2023.head()

,id_empresa,anio_inicio,periodo,id_sector_general,total_ingresos,personal_remunerado,gasto_remuneracion_personal,gasto_personal_total,personal_mujeres,personal_hombres,personal_ocupado,imp_ind_com,imp_otros,gasto_servicios_publicos,gasto_energia_electrica,gasto_gas_natural
0,10001,1992,2023,I1,3456999,39.0,981704,981704,20.0,19.0,39.0,40875,105032,149432,261404,93488
1,10002,1994,2023,I1,7226625,36.0,1065968,1113323,22.0,15.0,37.0,0,40081,215335,434207,100398
2,10003,2015,2023,I1,13894282,77.0,2394824,2422620,68.0,57.0,125.0,165248,60732,375316,1337866,182516
3,10004,2017,2023,I1,13249524,139.0,3211998,3234865,42.0,97.0,139.0,28396,15588,0,0,19800
4,10005,1957,2023,I2,46060505,119.0,4492465,5184918,114.0,142.0,256.0,176263,401643,490586,1851121,206658

Se unifican los datasets mediante un inner join con el id de la empresa

In [ ]:
# Merge de los dos datasets por campo id_empresa
df_servicios_unificado_2023 = pd.merge(df_ambiental_2023, df_general_2023, on="id_empresa", how="inner")
df_servicios_unificado_2023.head()

,id_empresa,periodo_x,id_sector,sector_desc,gastos_totales,gasto_gestion_amb,contrata_personal_amb,realiza_inv_red_emision_aire,realiza_inv_ahorro_agua,realiza_inv_inst_med_agua,...,gasto_remuneracion_personal,gasto_personal_total,personal_mujeres,personal_hombres,personal_ocupado,imp_ind_com,imp_otros,gasto_servicios_publicos,gasto_energia_electrica,gasto_gas_natural
0,10429,2023,H1,auxiliares del transporte,141276673,331267,1,1,1,0,...,36962309,38290814,202.0,388.0,590.0,963111,1648187,265462,5424628,541027
1,10213,2023,H1,auxiliares del transporte,141276673,331267,1,0,0,0,...,1584207,1659610,12.0,25.0,37.0,312373,14639,57941,429605,2841743
2,13851,2023,H1,auxiliares del transporte,141276673,331267,1,0,0,0,...,128737638,154540602,2028.0,2512.0,4540.0,3531354,332845,1175868,7060005,310316
3,10439,2023,H1,auxiliares del transporte,34597790,180809,1,0,0,0,...,13924889,14837246,89.0,118.0,207.0,578825,464589,3384,60044,0
4,13853,2023,H1,auxiliares del transporte,34597790,180809,0,0,0,0,...,8853484,9687587,86.0,121.0,207.0,223278,804878,513354,1592513,31097

In [ ]:
# inspecciona el dataframe unificado
df_servicios_unificado_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6211 entries, 0 to 6210
Data columns (total 39 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id_empresa                       6211 non-null   int64
 1   periodo_x                        6211 non-null   int64
 2   id_sector                        6211 non-null   object
 3   sector_desc                      6211 non-null   object
 4   gastos_totales                   6211 non-null   int64
 5   gasto_gestion_amb                6211 non-null   int64
 6   contrata_personal_amb            6211 non-null   int64
 7   realiza_inv_red_emision_aire     6211 non-null   int64
 8   realiza_inv_ahorro_agua          6211 non-null   int64
 9   realiza_inv_inst_med_agua        6211 non-null   int64
 10  realiza_inv_disp_desechos        6211 non-null   int64
 11  realiza_inv_protec_suelo         6211 non-null   int64
 12  realiza_inv_evita_ruido_vibra    6211 non-null   int64
 13  realiza_inv_energia_limp         6211 non-null   int64
 14  realiza_otras_inv_amb            6211 non-null   int64
 15  realiza_gasto_red_emision_aire   6211 non-null   int64
 16  realiza_gasto_ahorro_agua        6211 non-null   int64
 17  realiza_gasto_inst_med_agua      6211 non-null   int64
 18  realiza_gasto_disp_desechos      6211 non-null   int64
 19  realiza_gasto_protec_suelo       6211 non-null   int64
 20  realiza_gasto_evita_ruido_vibra  6211 non-null   int64
 21  realiza_gasto_terceros_amb       6211 non-null   int64
 22  realiza_gasto_energia_limp       6211 non-null   int64
 23  realiza_otros_gastos_amb         6211 non-null   int64
 24  anio_inicio                      6211 non-null   int64
 25  periodo_y                        6211 non-null   int64
 26  id_sector_general                6211 non-null   object
 27  total_ingresos                   6211 non-null   object
 28  personal_remunerado              6211 non-null   float64
 29  gasto_remuneracion_personal      6211 non-null   int64
 30  gasto_personal_total             6211 non-null   int64
 31  personal_mujeres                 6211 non-null   float64
 32  personal_hombres                 6211 non-null   float64
 33  personal_ocupado                 6211 non-null   float64
 34  imp_ind_com                      6211 non-null   object
 35  imp_otros                        6211 non-null   object
 36  gasto_servicios_publicos         6211 non-null   int64
 37  gasto_energia_electrica          6211 non-null   object
 38  gasto_gas_natural                6211 non-null   object
dtypes: float64(4), int64(27), object(8)
memory usage: 1.8+ MB

Existen columnas con el mismo nombre en ambos datasets, por lo tanto pandas les modifica el nombre, a continuación se deja una sola con el nombre original.

In [ ]:
# Elimina columna periodo repetida
df_servicios_unificado_2023.drop(columns=["periodo_y"], inplace=True)
df_servicios_unificado_2023.rename(columns={"periodo_x":"periodo"}, inplace=True)
print(df_servicios_unificado_2023.columns)

Index(['id_empresa', 'periodo', 'id_sector', 'sector_desc', 'gastos_totales',
       'gasto_gestion_amb', 'contrata_personal_amb',
       'realiza_inv_red_emision_aire', 'realiza_inv_ahorro_agua',
       'realiza_inv_inst_med_agua', 'realiza_inv_disp_desechos',
       'realiza_inv_protec_suelo', 'realiza_inv_evita_ruido_vibra',
       'realiza_inv_energia_limp', 'realiza_otras_inv_amb',
       'realiza_gasto_red_emision_aire', 'realiza_gasto_ahorro_agua',
       'realiza_gasto_inst_med_agua', 'realiza_gasto_disp_desechos',
       'realiza_gasto_protec_suelo', 'realiza_gasto_evita_ruido_vibra',
       'realiza_gasto_terceros_amb', 'realiza_gasto_energia_limp',
       'realiza_otros_gastos_amb', 'anio_inicio', 'id_sector_general',
       'total_ingresos', 'personal_remunerado', 'gasto_remuneracion_personal',
       'gasto_personal_total', 'personal_mujeres', 'personal_hombres',
       'personal_ocupado', 'imp_ind_com', 'imp_otros',
       'gasto_servicios_publicos', 'gasto_energia_electrica',
       'gasto_gas_natural'],
      dtype='object')

## Verificación de consistencia de id_empresa e id_sector
Se comparan los id_sector e id_sector_general, y si son inconsistentes se busca la razón para realizar ajustes o eliminar registros.

In [ ]:
# Extrae id_sector diferentes
condicion_diferente_Sector = df_servicios_unificado_2023['id_sector'] != df_servicios_unificado_2023['id_sector_general']
df_servicios_unificado_2023.loc[condicion_diferente_Sector,
                                ['id_empresa',
                                 'id_sector',
                                 'total_ingresos',
                                 'id_sector_general']]

      id_empresa id_sector total_ingresos id_sector_general
54         21052        I2       31999563                 Q
108        20927        J4       12815089                N3
110        20857        J4      136624633                 Q
124        20925        J4       14644693                H1
127        18208        LN       94668755               LN1
...          ...       ...            ...               ...
5890       20991         Q       15495119                N4
5901       20898         R      210285510                N3
5913       20964         R        5897285                M1
5914       20985         R       21623667                N3
5915       20987         R       22219164                N3

[493 rows x 4 columns]

Se evidencia que el sector "LN1" en id_sector_general tiene un número extra, se puede ajustar a "LN" para que coincida sin modificar los datos. Por otro lado, existen id_sector que no tienen relación, se aislan y se eliminan del análisis estos registros.

In [ ]:
# Corrige id_sector_general LN1 a LN
df_servicios_unificado_2023['id_sector_general'] = df_servicios_unificado_2023['id_sector_general'].mask(df_servicios_unificado_2023['id_sector_general']=='LN1', 'LN')
condicion_diferente_Sector = df_servicios_unificado_2023['id_sector'] != df_servicios_unificado_2023['id_sector_general']
df_servicios_unificado_2023.loc[condicion_diferente_Sector,
                                ['id_empresa',
                                 'id_sector',
                                 'total_ingresos',
                                 'id_sector_general']]

      id_empresa id_sector total_ingresos id_sector_general
54         21052        I2       31999563                 Q
108        20927        J4       12815089                N3
110        20857        J4      136624633                 Q
124        20925        J4       14644693                H1
137        20899        LN       84868861                 R
...          ...       ...            ...               ...
5890       20991         Q       15495119                N4
5901       20898         R      210285510                N3
5913       20964         R        5897285                M1
5914       20985         R       21623667                N3
5915       20987         R       22219164                N3

[175 rows x 4 columns]

In [ ]:
# Elimina registros con incongruencias en id_sector e id_sector_general
df_servicios_unificado_2023 = df_servicios_unificado_2023[df_servicios_unificado_2023['id_sector'] == df_servicios_unificado_2023['id_sector_general']]
df_servicios_unificado_2023.shape

(6036, 38)

In [ ]:
# Verifica id_sector
condicion_diferente_Sector = df_servicios_unificado_2023['id_sector'] != df_servicios_unificado_2023['id_sector_general']
df_servicios_unificado_2023.loc[condicion_diferente_Sector,
                                ['id_empresa',
                                 'id_sector',
                                 'total_ingresos',
                                 'id_sector_general']]

Empty DataFrame
Columns: [id_empresa, id_sector, total_ingresos, id_sector_general]
Index: []

Se eliminaron satisfactoriamente los registros con id_sector inconsistentes

## Exporta datos
Exporta el dataframe unificado a la carpeta de datasets unificados

In [ ]:
# Exporta el dataframe como csv
df_servicios_unificado_2023.to_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/unificados/2023_eas_unificado.csv", index=False)