<a href="https://colab.research.google.com/github/Schiavi13/analisis-impacto-covid19-en-inversion-ecoeficiencia-empresarial-2019-2023/blob/luis_001/src/merge_datasets_ambiental_general_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Unificación de datasets ambiental y general del año 2022

In [ ]:
# importar librerias
import pandas as pd
print("Carga de librerías exitosa")

Carga de librerías exitosa

In [ ]:
# Carga datasets ambiental y general
df_ambiental_2022 = pd.read_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/ambiental/2022_eas_ambiental.csv")
df_ambiental_2022.head()

,id_empresa,periodo,id_sector,sector_desc,gastos_totales,gasto_gestion_amb,contrata_personal_amb,realiza_inv_red_emision_aire,realiza_inv_ahorro_agua,realiza_inv_inst_med_agua,...,realiza_otras_inv_amb,realiza_gasto_red_emision_aire,realiza_gasto_ahorro_agua,realiza_gasto_inst_med_agua,realiza_gasto_disp_desechos,realiza_gasto_protec_suelo,realiza_gasto_evita_ruido_vibra,realiza_gasto_terceros_amb,realiza_gasto_energia_limp,realiza_otros_gastos_amb
0,10430,2022,H1,auxiliares del transporte,47609563,293768,1,0,0,1,...,0,0,0,0,1,0,0,1,0,0
1,10429,2022,H1,auxiliares del transporte,47609563,293768,0,0,0,1,...,1,1,1,0,1,0,1,1,0,1
2,18513,2022,H1,auxiliares del transporte,47609563,293768,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,13853,2022,H1,auxiliares del transporte,29336128,139752,0,0,0,0,...,0,1,0,0,1,1,1,1,0,0
4,15179,2022,H1,auxiliares del transporte,29336128,139752,1,0,0,0,...,1,0,0,0,1,0,0,1,0,0

In [ ]:
df_general_2022 = pd.read_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/general/2022_eas_general.csv")
df_general_2022.head()

,id_empresa,anio_inicio,periodo,id_sector_general,total_ingresos,personal_remunerado,gasto_remuneracion_personal,gasto_personal_total,personal_mujeres,personal_hombres,personal_ocupado,imp_ind_com,imp_otros,gasto_servicios_publicos,gasto_energia_electrica,gasto_gas_natural
0,10001,1992,2022,I1,3548177.0,33.0,763555,802943,15.0,18.0,33.0,43052,37494,130639,166584,91806
1,10002,1994,2022,I1,5652965.0,29.0,686505,718323,16.0,14.0,30.0,57144,147335,214130,404366,81375
2,10003,2015,2022,I1,12123841.0,51.0,1655246,1678311,51.0,63.0,114.0,144835,18332,296693,1249603,15457
3,10004,2017,2022,I1,15692721.0,136.0,2524379,2573519,136.0,0.0,136.0,11792,50025,0,0,43200
4,10005,1957,2022,I2,34356219.0,48.0,2663362,3157446,99.0,139.0,238.0,142812,388469,372088,1591866,141518

Se unifican los datasets mediante un inner join con el id de la empresa

In [ ]:
# Merge de los dos datasets por campo id_empresa
df_servicios_unificado_2022 = pd.merge(df_ambiental_2022, df_general_2022, on="id_empresa", how="inner")
df_servicios_unificado_2022.head()

,id_empresa,periodo_x,id_sector,sector_desc,gastos_totales,gasto_gestion_amb,contrata_personal_amb,realiza_inv_red_emision_aire,realiza_inv_ahorro_agua,realiza_inv_inst_med_agua,...,gasto_remuneracion_personal,gasto_personal_total,personal_mujeres,personal_hombres,personal_ocupado,imp_ind_com,imp_otros,gasto_servicios_publicos,gasto_energia_electrica,gasto_gas_natural
0,10430,2022,H1,auxiliares del transporte,47609563,293768,1,0,0,1,...,24034063,25753293,381.0,436.0,817.0,754774,1818584,286805,1071342,0
1,10429,2022,H1,auxiliares del transporte,47609563,293768,0,0,0,1,...,29445538,30774485,263.0,255.0,518.0,733848,1431522,231696,4570711,557029
2,18513,2022,H1,auxiliares del transporte,47609563,293768,1,0,0,0,...,2606974,2863189,13.0,46.0,59.0,300067,7571,50999,253701,859855
3,13853,2022,H1,auxiliares del transporte,29336128,139752,0,0,0,0,...,7656619,9089487,82.0,124.0,206.0,167995,856917,387510,1340117,28114
4,15179,2022,H1,auxiliares del transporte,29336128,139752,1,0,0,0,...,2916306,3008269,21.0,41.0,62.0,18689,183846,28871,252173,0

In [ ]:
# inspecciona el dataframe unificado
df_servicios_unificado_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6544 entries, 0 to 6543
Data columns (total 39 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id_empresa                       6544 non-null   int64
 1   periodo_x                        6544 non-null   int64
 2   id_sector                        6544 non-null   object
 3   sector_desc                      6544 non-null   object
 4   gastos_totales                   6544 non-null   int64
 5   gasto_gestion_amb                6544 non-null   int64
 6   contrata_personal_amb            6544 non-null   int64
 7   realiza_inv_red_emision_aire     6544 non-null   int64
 8   realiza_inv_ahorro_agua          6544 non-null   int64
 9   realiza_inv_inst_med_agua        6544 non-null   int64
 10  realiza_inv_disp_desechos        6544 non-null   int64
 11  realiza_inv_protec_suelo         6544 non-null   int64
 12  realiza_inv_evita_ruido_vibra    6544 non-null   int64
 13  realiza_inv_energia_limp         6544 non-null   int64
 14  realiza_otras_inv_amb            6544 non-null   int64
 15  realiza_gasto_red_emision_aire   6544 non-null   int64
 16  realiza_gasto_ahorro_agua        6544 non-null   int64
 17  realiza_gasto_inst_med_agua      6544 non-null   int64
 18  realiza_gasto_disp_desechos      6544 non-null   int64
 19  realiza_gasto_protec_suelo       6544 non-null   int64
 20  realiza_gasto_evita_ruido_vibra  6544 non-null   int64
 21  realiza_gasto_terceros_amb       6544 non-null   int64
 22  realiza_gasto_energia_limp       6544 non-null   int64
 23  realiza_otros_gastos_amb         6544 non-null   int64
 24  anio_inicio                      6544 non-null   int64
 25  periodo_y                        6544 non-null   int64
 26  id_sector_general                6544 non-null   object
 27  total_ingresos                   6543 non-null   float64
 28  personal_remunerado              6543 non-null   float64
 29  gasto_remuneracion_personal      6544 non-null   int64
 30  gasto_personal_total             6544 non-null   int64
 31  personal_mujeres                 6543 non-null   float64
 32  personal_hombres                 6543 non-null   float64
 33  personal_ocupado                 6543 non-null   float64
 34  imp_ind_com                      6544 non-null   object
 35  imp_otros                        6544 non-null   object
 36  gasto_servicios_publicos         6544 non-null   int64
 37  gasto_energia_electrica          6544 non-null   object
 38  gasto_gas_natural                6544 non-null   int64
dtypes: float64(5), int64(28), object(6)
memory usage: 1.9+ MB

Existen columnas con el mismo nombre en ambos datasets, por lo tanto pandas les modifica el nombre, a continuación se deja una sola con el nombre original.

In [ ]:
# Elimina columna periodo repetida
df_servicios_unificado_2022.drop(columns=["periodo_y"], inplace=True)
df_servicios_unificado_2022.rename(columns={"periodo_x":"periodo"}, inplace=True)
print(df_servicios_unificado_2022.columns)

Index(['id_empresa', 'periodo', 'id_sector', 'sector_desc', 'gastos_totales',
       'gasto_gestion_amb', 'contrata_personal_amb',
       'realiza_inv_red_emision_aire', 'realiza_inv_ahorro_agua',
       'realiza_inv_inst_med_agua', 'realiza_inv_disp_desechos',
       'realiza_inv_protec_suelo', 'realiza_inv_evita_ruido_vibra',
       'realiza_inv_energia_limp', 'realiza_otras_inv_amb',
       'realiza_gasto_red_emision_aire', 'realiza_gasto_ahorro_agua',
       'realiza_gasto_inst_med_agua', 'realiza_gasto_disp_desechos',
       'realiza_gasto_protec_suelo', 'realiza_gasto_evita_ruido_vibra',
       'realiza_gasto_terceros_amb', 'realiza_gasto_energia_limp',
       'realiza_otros_gastos_amb', 'anio_inicio', 'id_sector_general',
       'total_ingresos', 'personal_remunerado', 'gasto_remuneracion_personal',
       'gasto_personal_total', 'personal_mujeres', 'personal_hombres',
       'personal_ocupado', 'imp_ind_com', 'imp_otros',
       'gasto_servicios_publicos', 'gasto_energia_electrica',
       'gasto_gas_natural'],
      dtype='object')

## Verificación de consistencia de id_empresa e id_sector
Se comparan los id_sector e id_sector_general, y si son inconsistentes se busca la razón para realizar ajustes o eliminar registros.

In [ ]:
# Extrae id_sector diferentes
condicion_diferente_Sector = df_servicios_unificado_2022['id_sector'] != df_servicios_unificado_2022['id_sector_general']
df_servicios_unificado_2022.loc[condicion_diferente_Sector,
                                ['id_empresa',
                                 'id_sector',
                                 'total_ingresos',
                                 'id_sector_general']]

      id_empresa id_sector  total_ingresos id_sector_general
54         21052        I2      30712436.0                 Q
106        20927        J4      12685694.0                N3
119        20993        J4      12425785.0                N3
125        20925        J4       9663882.0                H1
127        13369        LN      17615780.0               LN1
...          ...       ...             ...               ...
6210       20997         Q      16928217.0                N3
6236       20898         R     163178586.0                N3
6247       20964         R       5477415.0                M1
6248       20985         R      16521337.0                N3
6249       20987         R      18437356.0                N3

[532 rows x 4 columns]

Se evidencia que el sector "LN1" en id_sector_general tiene un número extra, se puede ajustar a "LN" para que coincida sin modificar los datos. Por otro lado, existen id_sector que no tienen relación, se aislan y se eliminan del análisis estos registros.

In [ ]:
# Corrige id_sector_general LN1 a LN
df_servicios_unificado_2022['id_sector_general'] = df_servicios_unificado_2022['id_sector_general'].mask(df_servicios_unificado_2022['id_sector_general']=='LN1', 'LN')
condicion_diferente_Sector = df_servicios_unificado_2022['id_sector'] != df_servicios_unificado_2022['id_sector_general']
df_servicios_unificado_2022.loc[condicion_diferente_Sector,
                                ['id_empresa',
                                 'id_sector',
                                 'total_ingresos',
                                 'id_sector_general']]

      id_empresa id_sector  total_ingresos id_sector_general
54         21052        I2      30712436.0                 Q
106        20927        J4      12685694.0                N3
119        20993        J4      12425785.0                N3
125        20925        J4       9663882.0                H1
138        20899        LN      74871240.0                 R
...          ...       ...             ...               ...
6210       20997         Q      16928217.0                N3
6236       20898         R     163178586.0                N3
6247       20964         R       5477415.0                M1
6248       20985         R      16521337.0                N3
6249       20987         R      18437356.0                N3

[194 rows x 4 columns]

## Manejo de rechazados
Extrae los registros inconsistentes a un csv aparte.

In [ ]:
# Crea nuevo dataframe con datos inconsistentes
condicion_diferente_Sector = df_servicios_unificado_2022['id_sector'] != df_servicios_unificado_2022['id_sector_general']
df_rechazados_unificado_2022 = df_servicios_unificado_2022.loc[condicion_diferente_Sector,
                                ['id_empresa',
                                 'id_sector',
                                 'sector_desc',
                                 'id_sector_general']]
df_rechazados_unificado_2022

,id_empresa,id_sector,sector_desc,id_sector_general
54,21052,I2,expendio de alimentos,Q
106,20927,J4,inform y serv de informacion,N3
119,20993,J4,inform y serv de informacion,N3
125,20925,J4,inform y serv de informacion,H1
138,20899,LN,inmobiliarias y alquileres,R
...,...,...,...,...
6210,20997,Q,salud humana,N3
6236,20898,R,"actividades creativas, artisticas y de entretenim",N3
6247,20964,R,"actividades creativas, artisticas y de entretenim",M1
6248,20985,R,"actividades creativas, artisticas y de entretenim",N3
6249,20987,R,"actividades creativas, artisticas y de entretenim",N3

In [ ]:
# Exporta el dataframe con datos inconsistentes a csv
df_rechazados_unificado_2022.to_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/unificados/rechazados/2022_rechazados_eas_unificado.csv", index=False)

In [ ]:
# Elimina registros con incongruencias en id_sector e id_sector_general
df_servicios_unificado_2022 = df_servicios_unificado_2022[df_servicios_unificado_2022['id_sector'] == df_servicios_unificado_2022['id_sector_general']]
df_servicios_unificado_2022.shape

(6350, 38)

In [ ]:
# Verifica id_sector
condicion_diferente_Sector = df_servicios_unificado_2022['id_sector'] != df_servicios_unificado_2022['id_sector_general']
df_servicios_unificado_2022.loc[condicion_diferente_Sector,
                                ['id_empresa',
                                 'id_sector',
                                 'total_ingresos',
                                 'id_sector_general']]

Empty DataFrame
Columns: [id_empresa, id_sector, total_ingresos, id_sector_general]
Index: []

Se eliminaron satisfactoriamente los registros con id_sector inconsistentes

## Exporta datos
Exporta el dataframe unificado a la carpeta de datasets unificados

In [ ]:
# Exporta el dataframe como csv
df_servicios_unificado_2022.to_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/unificados/2022_eas_unificado.csv", index=False)