<a href="https://colab.research.google.com/github/Schiavi13/analisis-impacto-covid19-en-inversion-ecoeficiencia-empresarial-2019-2023/blob/luis_001/src/merge_datasets_ambiental_general_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Unificación de datasets ambiental y general del año 2020

In [ ]:
# importar librerias
import pandas as pd
print("Carga de librerías exitosa")

Carga de librerías exitosa

In [ ]:
# Carga datasets ambiental y general
df_ambiental_2020 = pd.read_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/ambiental/2020_eas_ambiental.csv")
df_ambiental_2020.head()

,id_empresa,periodo,id_sector,sector_desc,gastos_totales,gasto_gestion_amb,realiza_inv_red_emision_aire,realiza_inv_ahorro_agua,realiza_inv_inst_med_agua,realiza_inv_disp_desechos,...,realiza_otras_inv_amb,realiza_gasto_red_emision_aire,realiza_gasto_ahorro_agua,realiza_gasto_inst_med_agua,realiza_gasto_disp_desechos,realiza_gasto_protec_suelo,realiza_gasto_evita_ruido_vibra,realiza_gasto_terceros_amb,realiza_gasto_energia_limp,realiza_otros_gastos_amb
0,12366,2020,H1,auxiliares del transporte,136971770,1908989,0,0,0,0,...,1,1,1,1,1,1,1,1,0,1
1,10017,2020,H1,auxiliares del transporte,136971770,1908989,0,0,0,0,...,0,1,1,0,1,0,0,1,0,0
2,12283,2020,H1,auxiliares del transporte,136971771,1908990,0,1,1,1,...,0,0,1,1,1,0,0,0,0,0
3,14588,2020,H1,auxiliares del transporte,32549555,760566,0,0,0,0,...,0,1,1,1,0,0,0,0,0,0
4,12790,2020,H1,auxiliares del transporte,27354483,651317,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0

In [ ]:
df_general_2020 = pd.read_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/general/2020_eas_general.csv")
df_general_2020.head()

,id_empresa,anio_inicio,periodo,id_sector_general,total_ingresos,personal_remunerado,gasto_remuneracion_personal,gasto_personal_total,personal_mujeres,personal_hombres,personal_ocupado,imp_ind_com,imp_otros,gasto_servicios_publicos,gasto_energia_electrica,gasto_gas_natural
0,10001,1992.0,2020,I1,1278418,35.0,558884.0,589084.0,16.0,19.0,35.0,16299,8044,49545,155441,42913
1,10002,1994.0,2020,I1,1567963,39.0,914026.0,918226.0,18.0,22.0,40.0,685,51349,88627,221604,37144
2,10003,1999.0,2020,I1,6118734,59.0,1304459.0,1457018.0,38.0,61.0,99.0,74248,195254,152332,844994,133546
3,10004,2009.0,2020,I1,2744765,15.0,289083.0,289083.0,7.0,8.0,15.0,17826,19092,132456,154346,0
4,10005,1957.0,2020,I2,14030451,48.0,2221110.0,2457776.0,82.0,132.0,214.0,35213,343837,154906,691352,51924

Se unifican los datasets mediante un inner join con el id de la empresa

In [ ]:
# Merge de los dos datasets por campo id_empresa
df_servicios_unificado_2020 = pd.merge(df_ambiental_2020, df_general_2020, on="id_empresa", how="inner")
df_servicios_unificado_2020.head()

,id_empresa,periodo_x,id_sector,sector_desc,gastos_totales,gasto_gestion_amb,realiza_inv_red_emision_aire,realiza_inv_ahorro_agua,realiza_inv_inst_med_agua,realiza_inv_disp_desechos,...,gasto_remuneracion_personal,gasto_personal_total,personal_mujeres,personal_hombres,personal_ocupado,imp_ind_com,imp_otros,gasto_servicios_publicos,gasto_energia_electrica,gasto_gas_natural
0,12366,2020,H1,auxiliares del transporte,136971770,1908989,0,0,0,0,...,10470030.0,13153908.0,17.0,93.0,110.0,2385231,9408425,0,4921528,0
1,10017,2020,H1,auxiliares del transporte,136971770,1908989,0,0,0,0,...,23454419.0,28510222.0,146.0,417.0,563.0,1040490,321397,593380,2710306,0
2,12283,2020,H1,auxiliares del transporte,136971771,1908990,0,1,1,1,...,36677974.0,38419733.0,246.0,367.0,613.0,2960817,2611863,613544,10289922,0
3,14588,2020,H1,auxiliares del transporte,32549555,760566,0,0,0,0,...,8083130.0,9208247.0,50.0,79.0,129.0,581743,1573766,366798,1969881,0
4,12790,2020,H1,auxiliares del transporte,27354483,651317,0,0,0,0,...,7323128.0,7998114.0,80.0,135.0,215.0,574611,181292,176093,1551399,0

In [ ]:
# inspecciona el dataframe unificado
df_servicios_unificado_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6111 entries, 0 to 6110
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id_empresa                       6111 non-null   int64
 1   periodo_x                        6111 non-null   int64
 2   id_sector                        6111 non-null   object
 3   sector_desc                      6111 non-null   object
 4   gastos_totales                   6111 non-null   int64
 5   gasto_gestion_amb                6111 non-null   int64
 6   realiza_inv_red_emision_aire     6111 non-null   int64
 7   realiza_inv_ahorro_agua          6111 non-null   int64
 8   realiza_inv_inst_med_agua        6111 non-null   int64
 9   realiza_inv_disp_desechos        6111 non-null   int64
 10  realiza_inv_protec_suelo         6111 non-null   int64
 11  realiza_inv_evita_ruido_vibra    6111 non-null   int64
 12  realiza_inv_energia_limp         6111 non-null   int64
 13  realiza_otras_inv_amb            6111 non-null   int64
 14  realiza_gasto_red_emision_aire   6111 non-null   int64
 15  realiza_gasto_ahorro_agua        6111 non-null   int64
 16  realiza_gasto_inst_med_agua      6111 non-null   int64
 17  realiza_gasto_disp_desechos      6111 non-null   int64
 18  realiza_gasto_protec_suelo       6111 non-null   int64
 19  realiza_gasto_evita_ruido_vibra  6111 non-null   int64
 20  realiza_gasto_terceros_amb       6111 non-null   int64
 21  realiza_gasto_energia_limp       6111 non-null   int64
 22  realiza_otros_gastos_amb         6111 non-null   int64
 23  anio_inicio                      6110 non-null   float64
 24  periodo_y                        6111 non-null   int64
 25  id_sector_general                6111 non-null   object
 26  total_ingresos                   6111 non-null   object
 27  personal_remunerado              6111 non-null   float64
 28  gasto_remuneracion_personal      6111 non-null   float64
 29  gasto_personal_total             6111 non-null   float64
 30  personal_mujeres                 6111 non-null   float64
 31  personal_hombres                 6111 non-null   float64
 32  personal_ocupado                 6111 non-null   float64
 33  imp_ind_com                      6111 non-null   object
 34  imp_otros                        6111 non-null   object
 35  gasto_servicios_publicos         6111 non-null   object
 36  gasto_energia_electrica          6111 non-null   object
 37  gasto_gas_natural                6111 non-null   object
dtypes: float64(7), int64(22), object(9)
memory usage: 1.8+ MB

Existen columnas con el mismo nombre en ambos datasets, por lo tanto pandas les modifica el nombre, a continuación se deja una sola con el nombre original.

In [ ]:
# Elimina columna periodo repetida
df_servicios_unificado_2020.drop(columns=["periodo_y"], inplace=True)
df_servicios_unificado_2020.rename(columns={"periodo_x":"periodo"}, inplace=True)
print(df_servicios_unificado_2020.columns)

Index(['id_empresa', 'periodo', 'id_sector', 'sector_desc', 'gastos_totales',
       'gasto_gestion_amb', 'realiza_inv_red_emision_aire',
       'realiza_inv_ahorro_agua', 'realiza_inv_inst_med_agua',
       'realiza_inv_disp_desechos', 'realiza_inv_protec_suelo',
       'realiza_inv_evita_ruido_vibra', 'realiza_inv_energia_limp',
       'realiza_otras_inv_amb', 'realiza_gasto_red_emision_aire',
       'realiza_gasto_ahorro_agua', 'realiza_gasto_inst_med_agua',
       'realiza_gasto_disp_desechos', 'realiza_gasto_protec_suelo',
       'realiza_gasto_evita_ruido_vibra', 'realiza_gasto_terceros_amb',
       'realiza_gasto_energia_limp', 'realiza_otros_gastos_amb', 'anio_inicio',
       'id_sector_general', 'total_ingresos', 'personal_remunerado',
       'gasto_remuneracion_personal', 'gasto_personal_total',
       'personal_mujeres', 'personal_hombres', 'personal_ocupado',
       'imp_ind_com', 'imp_otros', 'gasto_servicios_publicos',
       'gasto_energia_electrica', 'gasto_gas_natural'],
      dtype='object')

## Verificación de consistencia de id_empresa e id_sector
Se comparan los id_sector e id_sector_general, y si son inconsistentes se busca la razón para realizar ajustes o eliminar registros.

In [ ]:
# Extrae id_sector diferentes
condicion_diferente_Sector = df_servicios_unificado_2020['id_sector'] != df_servicios_unificado_2020['id_sector_general']
df_servicios_unificado_2020.loc[condicion_diferente_Sector,
                                ['id_empresa',
                                 'id_sector',
                                 'total_ingresos',
                                 'id_sector_general']]

      id_empresa id_sector total_ingresos id_sector_general
2319       19825        LN        4242414               LN1
2320       13132        LN       42434899               LN1
2321       13844        LN      382566181               LN1
2322       11245        LN       27487365               LN1
2323       18208        LN       42215154               LN1
...          ...       ...            ...               ...
2629       19094        LN        6803300               LN1
2630       19709        LN        7245044               LN1
2631       15103        LN        3187523               LN1
2632       19115        LN        2573602               LN1
2633       16263        LN        3097826               LN1

[315 rows x 4 columns]

Se evidencia un patrón en las inconsistencias presentadas, el id_sector LN, aparece con un caracter de más "LN1", se ajusta para que coincidan

In [ ]:
# Corrige id_sector_general LN1 a LN
df_servicios_unificado_2020['id_sector_general'] = df_servicios_unificado_2020['id_sector_general'].mask(df_servicios_unificado_2020['id_sector_general']=='LN1', 'LN')
condicion_diferente_Sector = df_servicios_unificado_2020['id_sector'] != df_servicios_unificado_2020['id_sector_general']
df_servicios_unificado_2020.loc[condicion_diferente_Sector,
                                ['id_empresa',
                                 'id_sector',
                                 'total_ingresos',
                                 'id_sector_general']]

Empty DataFrame
Columns: [id_empresa, id_sector, total_ingresos, id_sector_general]
Index: []

In [ ]:
# Elimina registros con incongruencias en id_sector e id_sector_general
df_servicios_unificado_2020 = df_servicios_unificado_2020[df_servicios_unificado_2020['id_sector'] == df_servicios_unificado_2020['id_sector_general']]
df_servicios_unificado_2020.shape

(6111, 37)

Se eliminaron satisfactoriamente los registros con id_sector inconsistentes

## Exporta datos
Exporta el dataframe unificado a la carpeta de datasets unificados

In [ ]:
# Exporta el dataframe como csv
df_servicios_unificado_2020.to_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/unificados/2020_eas_unificado.csv", index=False)